site_title: Carrillo Tech Solutions
tagline: Engineered for Performance. Secured for the Future.
owner: Giovanni Carrillo
location: Cleveland, Ohio
email: Carrillo.giovanni215+carrillotech@outlook.com
twitch: supergman2155
youtube: supergman215
instagram: G.io215
linkedin: https://www.linkedin.com/in/giovanni-carrillo/
hero_headline: ‎ ‎ ‎ ‎ ‎
hero_sub: ‎
available: true
